name: CI — Tests & Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    name: tests-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # caches node_modules between runs

      - name: Install dependencies
        run: npm ci

      - name: Run tests (Vitest)
        run: npm run test:ci

      - name: Run build
        # run the same build command Vercel would run (vite, next, etc.)
        run: npm run build
